[project]
name = "progress-tracker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "pecific007", email = "pecific2007@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
progress-tracker = "progress_tracker:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
